// Dynamic Open Graph tags for barber booking links.
//
// Problem: when a barber shares toron.co.il/yossi-gidi to WhatsApp, the
// link preview is generated by the WhatsApp crawler reading the page's
// OG meta tags. Since we're an SPA, every URL returns the same static
// index.html — so every barber's link previews with Toron's generic
// branding instead of their own logo + business name.
//
// Solution: intercept requests for barber booking URLs at the worker
// edge, look up the barber's document, and rewrite the OG meta tags in
// the HTML before returning it. Crawlers see the barber's brand;
// regular users still get the same SPA (the OG tags are just hints,
// they don't affect runtime behavior).

import { loadServiceAccount, getAccessToken, firestoreGet, fieldVal } from './_lib.js';

// Routes that look like a barber slug but are actually app pages.
// MUST stay in sync with src/utils/slugs.js RESERVED_SLUGS.
const RESERVED = new Set([
  'auth', 'dashboard', 'settings', 'reports', 'pricing',
  'terms', 'privacy', 'refund', 'accessibility', 'promo',
  'onboarding', 'b', 'manage', 'api', 'whatsapp-templates',
  'admin', 'help', 'about', 'contact', 'support', 'home', 'index',
  'login', 'signup', 'register', 'logout', 'profile', 'account',
  'expenses', 'reviews', 'static', 'public', 'assets', 'src',
  'manifest', 'service-worker', 'sw', 'favicon', 'robots', 'sitemap',
]);

// Try to parse a barber-booking URL → return the slug to look up.
// Handles both `/b/<code>` (legacy) and `/<slug>` (custom).
export function parseBarberSlug(pathname) {
  const m = pathname.match(/^\/(?:b\/)?([a-z0-9][a-z0-9-]{1,29})\/?$/i);
  if (!m) return null;
  const slug = m[1].toLowerCase();
  if (RESERVED.has(slug)) return null;
  return slug;
}

// Resolve slug → barber data (logo, businessName, profession).
async function fetchBarberFromSlug(env, slug) {
  const svc = await loadServiceAccount(env);
  const token = await getAccessToken(svc);
  // shortCodes/{slug} → { uid }
  const code = await firestoreGet(svc, token, `shortCodes/${slug}`).catch(() => null);
  const uid = code ? fieldVal(code.fields?.uid) : null;
  if (!uid) return null;
  const barber = await firestoreGet(svc, token, `barbers/${uid}`).catch(() => null);
  if (!barber) return null;
  return {
    businessName: fieldVal(barber.fields?.businessName) || 'תור אצל בעל המקצוע',
    logoUrl: fieldVal(barber.fields?.logoUrl) || '',
    profession: fieldVal(barber.fields?.profession) || 'barber',
  };
}

// Photo IDs for the per-profession hero. Single source of truth — used
// by the in-page hero (responsive w=720/1080/1440, q=65). Mirrors the
// same map in src/pages/BookingPage.jsx; if you change one, change the
// other.
const PROFESSION_PHOTO_ID = {
  barber: '1503951914875-452162b0f3f1',
  manicurist: '1604654894610-df63bc536371',
  pedicurist: '1519415510236-718bdfcd89c8',
  cosmetician: '1616394584738-fc6e612e71b9',
};
const unsplashHero = (id, w) =>
  `https://images.unsplash.com/photo-${id}?w=${w}&q=65&auto=format&fit=crop`;

// OG fallback when a barber hasn't uploaded a logo — a Toron-branded
// 1200×630 PNG with the magenta→cyan rainbow + "Toron" mark. Lives in
// /public so it's served by the static asset binding. This keeps every
// shared booking link looking like Toron's brand even before the barber
// uploads their own logo.
const OG_FALLBACK = '/og-fallback.png';

function escapeHtml(s) {
  return String(s).replace(/[&<>"']/g, (c) => ({
    '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;',
  }[c]));
}

// Rewrites the relevant <meta> tags in index.html with per-barber values
// AND injects a high-priority preload link for the hero image. The
// preload kicks the right Unsplash photo into the browser's image cache
// before React even parses the JS bundle — so by the time BookingPage
// mounts its <img>, the bytes are already there and paint is instant.
function injectOgTags(html, barber, fullUrl) {
  const title = `${barber.businessName} — קביעת תור`;
  const desc = `קבעו תור ב-${barber.businessName} בקלות וביעילות. תורים זמינים עכשיו.`;
  // Prefer the barber's own logo. Fall back to the Toron-branded image
  // (NOT to Unsplash) so every link previews as a real branded asset.
  // Resolve to absolute URL so social crawlers can fetch it.
  const origin = new URL(fullUrl).origin;
  const ogImage = barber.logoUrl || `${origin}${OG_FALLBACK}`;
  const photoId = PROFESSION_PHOTO_ID[barber.profession] || PROFESSION_PHOTO_ID.barber;
  // Responsive preload via imagesrcset/imagesizes — modern browsers
  // (Chrome 116+, Safari 17+, Firefox 124+) pick the closest width to
  // 100vw at the current DPR. Older browsers fall back to `href` (1080w
  // covers most phones and laptops without bloating the request).
  const preloadHref = unsplashHero(photoId, 1080);
  const preloadSrcset = [
    `${unsplashHero(photoId, 720)} 720w`,
    `${unsplashHero(photoId, 1080)} 1080w`,
    `${unsplashHero(photoId, 1440)} 1440w`,
  ].join(', ');
  const tags = `
    <meta property="og:type" content="website" />
    <meta property="og:title" content="${escapeHtml(title)}" />
    <meta property="og:description" content="${escapeHtml(desc)}" />
    <meta property="og:image" content="${escapeHtml(ogImage)}" />
    <meta property="og:url" content="${escapeHtml(fullUrl)}" />
    <meta name="twitter:card" content="summary_large_image" />
    <meta name="twitter:title" content="${escapeHtml(title)}" />
    <meta name="twitter:description" content="${escapeHtml(desc)}" />
    <meta name="twitter:image" content="${escapeHtml(ogImage)}" />
    <link rel="preload" as="image"
      href="${escapeHtml(preloadHref)}"
      imagesrcset="${escapeHtml(preloadSrcset)}"
      imagesizes="100vw"
      fetchpriority="high" />`;
  return html
    .replace(
      /<title>[^<]*<\/title>/,
      `<title>${escapeHtml(title)}</title>`,
    )
    .replace(
      /<meta name="description"[^>]*\/?>/i,
      `<meta name="description" content="${escapeHtml(desc)}" />${tags}`,
    );
}

// Main handler — called from worker/index.js before falling through to
// env.ASSETS.fetch. Returns a Response if it handled the request, or
// `null` if the request should continue to the asset pipeline.
export async function maybeRewriteOg(request, env) {
  const url = new URL(request.url);
  const slug = parseBarberSlug(url.pathname);
  if (!slug) return null;
  // Get the raw index.html via the asset binding (returns the SPA shell)
  let assetResp;
  try {
    assetResp = await env.ASSETS.fetch(new Request(`${url.origin}/`, request));
  } catch { return null; }
  if (!assetResp.ok) return null;
  const ct = assetResp.headers.get('content-type') || '';
  if (!ct.includes('text/html')) return null;
  let html = await assetResp.text();
  // Best-effort barber lookup. If it fails (offline, missing) we just
  // serve the unmodified shell — the SPA will still render correctly.
  const barber = await fetchBarberFromSlug(env, slug).catch(() => null);
  if (!barber) return new Response(html, {
    status: 200,
    headers: { 'content-type': 'text/html; charset=utf-8', 'cache-control': 'public, max-age=0, must-revalidate' },
  });
  html = injectOgTags(html, barber, request.url);
  return new Response(html, {
    status: 200,
    headers: {
      'content-type': 'text/html; charset=utf-8',
      // Short cache so updates to the barber profile propagate quickly
      // to social previews but we still get edge caching benefits.
      'cache-control': 'public, max-age=300, s-maxage=300',
    },
  });
}
